name: Send Discord Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          description: |
            Nova atividade no repositório **${{ github.repository }}**!

            **Evento:** ${{ github.event_name }}
            **Autor:** ${{ github.actor }}
            **Commit:** `${{ github.event.head_commit.message }}`
            **Link:** [Ver commit](${{ github.event.head_commit.url }})